apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: ganeshsurna/expiration:latest
          env:
            - name: RABBITMQ_URL
              value: "amqps://yphsoosm:tyyM3r8PzRlzRDxjoJxod2HNU64_tQfB@fuji.lmq.cloudamqp.com/yphsoosm"
              # value: "amqp://rabbitmq-srv:5672"
# no port is needed for this to run.
# So, No need of service for expiration. Just a Pod(created by Deployment) is enough.